var myName = "Alex";
console.log(myName == "Alex");
console.log(myName !== "alex");
var myNumber = 10;
console.log(myNumber == 10);
console.log(myNumber !== 10);
console.log(myNumber > 5);
console.log(myNumber < 5);
console.log(myNumber <= 5);
console.log(myNumber >= 5);
var num1 = 10;
var num2 = 5;
console.log(num1 > 9 && num2 < 5);
console.log(num1 > 9 || num2 < 5);
var myArray = [2, 3, "John"];
var myString = "Shaun";
console.log(Array.isArray(myArray));
console.log(Array.isArray(myString));
